"""API-key creation, hashing, and authentication.

Why plain SHA-256 and not a slow password hash: keys are 256 bits of randomness
(generated by `secrets`), so they cannot be guessed or brute-forced the way passwords
can. A fast one-way hash is the standard choice and lets us look a key up by its hash.
The plaintext key is returned once at creation and is never stored or logged.
"""

import hashlib
import re
import secrets
from dataclasses import dataclass, field
from datetime import datetime

from sqlalchemy import select, update
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.types import utc_now
from app.models.api_key import ApiKey
from app.models.tenant import Tenant
from app.services.errors import InvalidInputError, UnknownTenantError

API_KEY_PREFIX = "tv_"
_API_KEY_PATTERN = re.compile(r"tv_[A-Za-z0-9_-]{43}")
_DISPLAY_PREFIX_LENGTH = 9


@dataclass(frozen=True)
class CreatedApiKey:
    """Returned once at creation. `plaintext` cannot be recovered later."""

    id: str
    tenant_id: str
    name: str
    key_prefix: str
    plaintext: str = field(repr=False)


@dataclass(frozen=True)
class ApiKeyPrincipal:
    """Who a valid key belongs to. The tenant always comes from here, never from the client."""

    tenant_id: str
    api_key_id: str
    tenant_active: bool


def generate_api_key() -> str:
    return API_KEY_PREFIX + secrets.token_urlsafe(32)


def is_well_formed_api_key(value: str) -> bool:
    return _API_KEY_PATTERN.fullmatch(value) is not None


def hash_api_key(key: str) -> str:
    return hashlib.sha256(key.encode("utf-8")).hexdigest()


async def create_api_key(session: AsyncSession, *, tenant_id: str, name: str) -> CreatedApiKey:
    clean_name = name.strip()
    if not 1 <= len(clean_name) <= 100:
        raise InvalidInputError("API key name must be 1 to 100 characters.")

    existing_tenant = (
        await session.execute(select(Tenant.id).where(Tenant.id == tenant_id))
    ).scalar_one_or_none()
    if existing_tenant is None:
        raise UnknownTenantError("Tenant does not exist.")

    plaintext = generate_api_key()
    row = ApiKey(
        tenant_id=tenant_id,
        name=clean_name,
        key_prefix=plaintext[:_DISPLAY_PREFIX_LENGTH],
        key_hash=hash_api_key(plaintext),
    )
    session.add(row)
    try:
        await session.flush()
    except IntegrityError as exc:
        await session.rollback()
        raise InvalidInputError("The API key could not be created.") from exc
    return CreatedApiKey(
        id=row.id,
        tenant_id=row.tenant_id,
        name=row.name,
        key_prefix=row.key_prefix,
        plaintext=plaintext,
    )


async def authenticate_api_key(session: AsyncSession, presented: str) -> ApiKeyPrincipal | None:
    """Return the owner of a valid, unrevoked key, or None for any kind of invalid key.

    Unknown, malformed, and revoked keys all give the same answer (None) so callers
    cannot learn which keys exist.
    """
    if not is_well_formed_api_key(presented):
        return None
    statement = (
        select(ApiKey.id, ApiKey.tenant_id, ApiKey.revoked_at, Tenant.is_active)
        .join(Tenant, Tenant.id == ApiKey.tenant_id)
        .where(ApiKey.key_hash == hash_api_key(presented))
    )
    row = (await session.execute(statement)).first()
    if row is None or row.revoked_at is not None:
        return None
    return ApiKeyPrincipal(
        tenant_id=row.tenant_id,
        api_key_id=row.id,
        tenant_active=bool(row.is_active),
    )


async def revoke_api_key(session: AsyncSession, *, tenant_id: str, api_key_id: str) -> bool:
    """Revoke one key belonging to the given tenant. Returns False if nothing was revoked."""
    revoked_at: datetime = utc_now()
    result = await session.execute(
        update(ApiKey)
        .where(
            ApiKey.id == api_key_id,
            ApiKey.tenant_id == tenant_id,
            ApiKey.revoked_at.is_(None),
        )
        .values(revoked_at=revoked_at)
    )
    return result.rowcount > 0
  
